---
namespace: trippsc2
name: hashi_vault
version: 1.7.0
readme: README.md
authors:
  - Jim Tarpley
description: This collection extends the community.hashi_vault collection with additional functionality.

license_file: 'LICENSE'

tags:
  - application
  - infrastructure
  - linux
  - security
  - tools

dependencies:
  ansible.posix: ">=1.0.0"
  community.hashi_vault: ">=6.2.0"
  trippsc2.general: ">=2.8.0"

repository: https://github.com/trippsc2/ansible-collection-hashi_vault.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
