---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: testing
  description: This role configures Hashicorp Vault in development mode for use in Molecule testing.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Debian
    versions:
      - trixie
      - bookworm
  - name: EL
    versions:
      - '9'
      - '8'
  - name: Ubuntu
    versions:
      - noble
      - jammy

collections:
  - ansible.posix
  - community.general

dependencies:
  - role: trippsc2.hashicorp.repo
