---
name: Molecule - install role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/install/**
      - '!roles/install/.aar_doc.yml'
      - '!roles/install/README.md'
      - '!roles/install/meta/argument_specs.yml'
      - '!roles/install/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/install/**
      - '!roles/install/.aar_doc.yml'
      - '!roles/install/README.md'
      - '!roles/install/meta/argument_specs.yml'
      - '!roles/install/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.hashi_vault'
jobs:
  molecule_raft_standalone:
    name: Run Molecule tests - Raft standalone
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian13_base
          - debian12_base
          - fedora42_base
          - fedora41_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.hashi_vault'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/install
          molecule test -s raft_standalone
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
  molecule_raft_cluster:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12_base
          - fedora42_base
          - fedora41_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.hashi_vault'
      - name: Run Molecule tests - Raft cluster
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/install
          molecule test -s raft_cluster
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
