---
name: Molecule - testing role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/testing/**
      - '!roles/testing/.aar_doc.yml'
      - '!roles/testing/README.md'
      - '!roles/testing/meta/argument_specs.yml'
      - '!roles/testing/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/testing/**
      - '!roles/testing/.aar_doc.yml'
      - '!roles/testing/README.md'
      - '!roles/testing/meta/argument_specs.yml'
      - '!roles/testing/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.hashi_vault'
jobs:
  molecule:
    name: Run Molecule tests
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.hashi_vault'
      role_name: 'testing'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian13_base
          - debian12_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
